// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * StationView is the JSON-friendly station projection exposed to the frontend.
 */
export class StationView {
    "uuid": string;
    "name": string;
    "streamUrl": string;
    "homepage": string;
    "favicon": string;
    "country": string;
    "tags": string;
    "bitrate": number;
    "codec": string;
    "votes": number;
    "clicks": number;

    /** Creates a new StationView instance. */
    constructor($$source: Partial<StationView> = {}) {
        if (!("uuid" in $$source)) {
            this["uuid"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("streamUrl" in $$source)) {
            this["streamUrl"] = "";
        }
        if (!("homepage" in $$source)) {
            this["homepage"] = "";
        }
        if (!("favicon" in $$source)) {
            this["favicon"] = "";
        }
        if (!("country" in $$source)) {
            this["country"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = "";
        }
        if (!("bitrate" in $$source)) {
            this["bitrate"] = 0;
        }
        if (!("codec" in $$source)) {
            this["codec"] = "";
        }
        if (!("votes" in $$source)) {
            this["votes"] = 0;
        }
        if (!("clicks" in $$source)) {
            this["clicks"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StationView instance from a string or object.
     */
    static createFrom($$source: any = {}): StationView {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StationView($$parsedSource as Partial<StationView>);
    }
}
