// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * QueueTrack holds metadata for a track in the play queue.
 */
export class QueueTrack {
    /**
     * Creates a new QueueTrack instance.
     * @param {Partial<QueueTrack>} [$$source = {}] - The source object to create the QueueTrack.
     */
    constructor($$source = {}) {
        if (!("trackId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["album"] = "";
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueTrack instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueueTrack}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueueTrack(/** @type {Partial<QueueTrack>} */($$parsedSource));
    }
}
