// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * QueueTrack holds metadata for a track in the play queue.
 */
export class QueueTrack {
    "trackId": number;
    "title": string;
    "artist": string;
    "album": string;
    "durationMs": number;
    "filePath": string;

    /** Creates a new QueueTrack instance. */
    constructor($$source: Partial<QueueTrack> = {}) {
        if (!("trackId" in $$source)) {
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            this["album"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueTrack instance from a string or object.
     */
    static createFrom($$source: any = {}): QueueTrack {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new QueueTrack($$parsedSource as Partial<QueueTrack>);
    }
}

/**
 * Toast represents a notification message for the frontend.
 */
export class Toast {
    "message": string;

    /**
     * "info", "warn", "error"
     */
    "type": string;

    /** Creates a new Toast instance. */
    constructor($$source: Partial<Toast> = {}) {
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Toast instance from a string or object.
     */
    static createFrom($$source: any = {}): Toast {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Toast($$parsedSource as Partial<Toast>);
    }
}
