// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GreetService is a demo service to prove the Go<->Frontend bridge works.
 * This will be replaced with real services (player, library, etc.) in later stories.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Greet(name: string): $CancellablePromise<string> {
    return $Call.ByID(1411160069, name);
}
