// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService exposes the music library to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "./internal/library/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AlbumArtwork returns the artwork for an album as a base64 data URI.
 */
export function AlbumArtwork(albumID: number): $CancellablePromise<string> {
    return $Call.ByID(866920135, albumID);
}

/**
 * GetAlbumTracks returns the tracks for a given album.
 */
export function GetAlbumTracks(albumID: number): $CancellablePromise<$models.AlbumTrack[]> {
    return $Call.ByID(207489145, albumID).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAlbums returns all albums sorted by the given field and direction.
 */
export function GetAlbums(sort: string, order: string): $CancellablePromise<$models.Album[]> {
    return $Call.ByID(1337880606, sort, order).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Search searches the library for tracks matching the query.
 */
export function Search(query: string, limit: number): $CancellablePromise<library$0.SearchResult[]> {
    return $Call.ByID(2206755262, query, limit).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AlbumTrack.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Album.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = library$0.SearchResult.createFrom;
const $$createType5 = $Create.Array($$createType4);
