// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService exposes the music library to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as radio$0 from "./internal/radio/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCustomRadioStation saves a user-defined radio station.
 */
export function AddCustomRadioStation(name: string, streamURL: string, faviconURL: string, homepage: string, tags: string): $CancellablePromise<$models.RadioCustomStationJSON> {
    return $Call.ByID(3781401643, name, streamURL, faviconURL, homepage, tags).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * AddMusicDirectory stores a local music library root.
 */
export function AddMusicDirectory(path: string): $CancellablePromise<void> {
    return $Call.ByID(1886803159, path);
}

/**
 * AddRadioFavourite saves a radio station to favourites.
 */
export function AddRadioFavourite(stationUUID: string, name: string, streamURL: string, faviconURL: string, homepage: string, tags: string, country: string, codec: string, bitrate: number): $CancellablePromise<void> {
    return $Call.ByID(3744144887, stationUUID, name, streamURL, faviconURL, homepage, tags, country, codec, bitrate);
}

/**
 * AddServer adds a new streaming server configuration.
 */
export function AddServer(cfg: $models.ServerConfig): $CancellablePromise<void> {
    return $Call.ByID(477958106, cfg);
}

/**
 * AddTrackToPlaylist adds a track to a playlist.
 */
export function AddTrackToPlaylist(playlistID: number, trackID: number): $CancellablePromise<void> {
    return $Call.ByID(2287316659, playlistID, trackID);
}

/**
 * AlbumArtwork returns the artwork for an album as a base64 data URI.
 */
export function AlbumArtwork(albumID: number): $CancellablePromise<string> {
    return $Call.ByID(866920135, albumID);
}

/**
 * ClearRadioHistory removes all radio playback history.
 */
export function ClearRadioHistory(): $CancellablePromise<void> {
    return $Call.ByID(2733979162);
}

/**
 * CompleteLastFmAuth exchanges the authorized token for a session key.
 */
export function CompleteLastFmAuth(token: string): $CancellablePromise<void> {
    return $Call.ByID(3698942302, token);
}

/**
 * ConnectListenBrainz validates the user token, retrieves the username, and saves
 * the configuration with scrobbling enabled.
 */
export function ConnectListenBrainz(userToken: string): $CancellablePromise<void> {
    return $Call.ByID(1138196949, userToken);
}

/**
 * CreatePlaylist creates a new playlist and returns its ID.
 */
export function CreatePlaylist(name: string): $CancellablePromise<number> {
    return $Call.ByID(4167498172, name);
}

/**
 * DeleteCustomRadioStation removes a user-defined radio station.
 */
export function DeleteCustomRadioStation(stationUUID: string): $CancellablePromise<void> {
    return $Call.ByID(3260428599, stationUUID);
}

/**
 * DeletePlaylist deletes a playlist.
 */
export function DeletePlaylist(id: number): $CancellablePromise<void> {
    return $Call.ByID(2018893399, id);
}

/**
 * DeleteServer removes a streaming server configuration.
 */
export function DeleteServer(id: string): $CancellablePromise<void> {
    return $Call.ByID(3862467038, id);
}

/**
 * DisconnectLastFm clears the Last.fm session key and username.
 */
export function DisconnectLastFm(): $CancellablePromise<void> {
    return $Call.ByID(970487533);
}

/**
 * DisconnectListenBrainz clears the ListenBrainz token and username.
 */
export function DisconnectListenBrainz(): $CancellablePromise<void> {
    return $Call.ByID(902147985);
}

/**
 * ExportUserConfig writes the canonical config file from current database state.
 */
export function ExportUserConfig(): $CancellablePromise<string> {
    return $Call.ByID(63490165);
}

/**
 * ExportUserConfigToPath writes user configuration to the given path.
 */
export function ExportUserConfigToPath(path: string): $CancellablePromise<void> {
    return $Call.ByID(1374680739, path);
}

/**
 * GetAlbumTracks returns the tracks for a given album.
 */
export function GetAlbumTracks(albumID: number): $CancellablePromise<$models.AlbumTrack[]> {
    return $Call.ByID(207489145, albumID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetAlbums returns all albums sorted by the given field and direction.
 * Source: "" (all, deduped), "local", "server".
 */
export function GetAlbums(sort: string, order: string, source: string): $CancellablePromise<$models.Album[]> {
    return $Call.ByID(1337880606, sort, order, source).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetAppPreferences returns product-level preferences.
 */
export function GetAppPreferences(): $CancellablePromise<$models.AppPreferencesJSON> {
    return $Call.ByID(3910505449).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * GetArtistByName returns the artist ID for the given name.
 */
export function GetArtistByName(name: string): $CancellablePromise<number> {
    return $Call.ByID(1148779767, name);
}

/**
 * GetArtistInfo returns metadata for the named artist, using cache with 30-day TTL.
 */
export function GetArtistInfo(artistName: string): $CancellablePromise<$models.ArtistInfoJSON> {
    return $Call.ByID(2345670893, artistName).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * GetCustomRadioStations returns user-defined radio stations.
 */
export function GetCustomRadioStations(): $CancellablePromise<$models.RadioCustomStationJSON[]> {
    return $Call.ByID(2495430549).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetListenBrainzConfig returns the current ListenBrainz configuration.
 */
export function GetListenBrainzConfig(): $CancellablePromise<$models.ListenBrainzConfigJSON> {
    return $Call.ByID(1867711289).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * GetMusicDirectories returns configured local music library roots.
 */
export function GetMusicDirectories(): $CancellablePromise<string[]> {
    return $Call.ByID(2414175136).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetPlaylistTracks returns the tracks in a playlist.
 */
export function GetPlaylistTracks(playlistID: number): $CancellablePromise<$models.PlaylistTrack[]> {
    return $Call.ByID(4244880336, playlistID).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetPlaylists returns all playlists.
 */
export function GetPlaylists(): $CancellablePromise<$models.Playlist[]> {
    return $Call.ByID(1524576557).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetRadioFavouritePinned reports whether a favourite station is pinned.
 */
export function GetRadioFavouritePinned(stationUUID: string): $CancellablePromise<boolean> {
    return $Call.ByID(4094481906, stationUUID);
}

/**
 * GetRadioFavourites returns all saved radio stations.
 */
export function GetRadioFavourites(): $CancellablePromise<$models.RadioFavouriteJSON[]> {
    return $Call.ByID(590575721).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * GetRadioHistory returns recently played radio stations.
 */
export function GetRadioHistory(limit: number): $CancellablePromise<$models.RadioHistoryJSON[]> {
    return $Call.ByID(3857005579, limit).then(($result: any) => {
        return $$createType17($result);
    });
}

/**
 * GetRadioStationByUUID returns full station metadata, fetching from RadioBrowser when possible.
 */
export function GetRadioStationByUUID(stationUUID: string): $CancellablePromise<$models.RadioStationJSON> {
    return $Call.ByID(4150278773, stationUUID).then(($result: any) => {
        return $$createType18($result);
    });
}

/**
 * GetRadioStationsByCountry returns radio stations matching a country.
 */
export function GetRadioStationsByCountry(country: string, limit: number): $CancellablePromise<$models.RadioStationJSON[]> {
    return $Call.ByID(3988982917, country, limit).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * GetRadioStationsByTag returns radio stations matching a tag.
 */
export function GetRadioStationsByTag(tag: string, limit: number): $CancellablePromise<$models.RadioStationJSON[]> {
    return $Call.ByID(3897998615, tag, limit).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * GetRecentlyPlayed returns the most recently played tracks.
 */
export function GetRecentlyPlayed(limit: number): $CancellablePromise<$models.RecentPlayJSON[]> {
    return $Call.ByID(3884039413, limit).then(($result: any) => {
        return $$createType21($result);
    });
}

/**
 * GetScrobbleConfig returns the current Last.fm scrobble configuration.
 */
export function GetScrobbleConfig(): $CancellablePromise<$models.ScrobbleConfigJSON> {
    return $Call.ByID(3948527462).then(($result: any) => {
        return $$createType22($result);
    });
}

/**
 * GetScrobbleQueueSize returns the number of scrobbles waiting for retry.
 */
export function GetScrobbleQueueSize(): $CancellablePromise<number> {
    return $Call.ByID(4199289054);
}

/**
 * GetServerStatuses returns the online/offline status of all configured servers.
 */
export function GetServerStatuses(): $CancellablePromise<$models.ServerStatusJSON[]> {
    return $Call.ByID(1839345631).then(($result: any) => {
        return $$createType24($result);
    });
}

/**
 * GetServers returns all configured streaming servers.
 */
export function GetServers(): $CancellablePromise<$models.ServerConfig[]> {
    return $Call.ByID(3711954650).then(($result: any) => {
        return $$createType26($result);
    });
}

/**
 * GetSomaFMStations returns all SomaFM channels.
 */
export function GetSomaFMStations(): $CancellablePromise<$models.RadioStationJSON[]> {
    return $Call.ByID(3406641218).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * GetTopAlbums returns the most-played albums for the given period.
 */
export function GetTopAlbums(period: string, limit: number): $CancellablePromise<$models.StatEntryJSON[]> {
    return $Call.ByID(1740480677, period, limit).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * GetTopArtists returns the most-played artists for the given period.
 */
export function GetTopArtists(period: string, limit: number): $CancellablePromise<$models.StatEntryJSON[]> {
    return $Call.ByID(2628386383, period, limit).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * GetTopClickedRadioStations returns the most clicked radio stations.
 */
export function GetTopClickedRadioStations(limit: number): $CancellablePromise<$models.RadioStationJSON[]> {
    return $Call.ByID(46869912, limit).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * GetTopTracks returns the most-played tracks for the given period.
 */
export function GetTopTracks(period: string, limit: number): $CancellablePromise<$models.StatEntryJSON[]> {
    return $Call.ByID(3437861925, period, limit).then(($result: any) => {
        return $$createType28($result);
    });
}

/**
 * GetTopVotedRadioStations returns the top voted radio stations.
 */
export function GetTopVotedRadioStations(limit: number): $CancellablePromise<$models.RadioStationJSON[]> {
    return $Call.ByID(1723581283, limit).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * GetUserConfigPath returns the canonical config file path (~/.config/forte/config.toml).
 */
export function GetUserConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(198184712);
}

/**
 * ImportUserConfig loads and merges the canonical config file (same rules as startup).
 */
export function ImportUserConfig(): $CancellablePromise<$models.UserConfigImportResultJSON> {
    return $Call.ByID(188952206).then(($result: any) => {
        return $$createType29($result);
    });
}

/**
 * ImportUserConfigFromPath loads and applies a config file from path.
 */
export function ImportUserConfigFromPath(path: string): $CancellablePromise<$models.UserConfigImportResultJSON> {
    return $Call.ByID(2145098713, path).then(($result: any) => {
        return $$createType29($result);
    });
}

/**
 * IsRadioFavourite checks if a station is in favourites.
 */
export function IsRadioFavourite(stationUUID: string): $CancellablePromise<boolean> {
    return $Call.ByID(329793224, stationUUID);
}

/**
 * MoveTrackInPlaylist moves a track from one position to another.
 */
export function MoveTrackInPlaylist(playlistID: number, fromPos: number, toPos: number): $CancellablePromise<void> {
    return $Call.ByID(465154155, playlistID, fromPos, toPos);
}

/**
 * OpenURL opens an http(s) URL in the system browser.
 */
export function OpenURL(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(1380764543, rawURL);
}

/**
 * ProxyImageURL fetches a remote image and returns it as a base64 data URI.
 * Results are cached in memory. Concurrent requests for the same URL are
 * coalesced into a single HTTP fetch. Returns empty string on failure.
 */
export function ProxyImageURL(url: string): $CancellablePromise<string> {
    return $Call.ByID(1305746552, url);
}

/**
 * RemoveMusicDirectory removes a local music library root.
 */
export function RemoveMusicDirectory(path: string): $CancellablePromise<void> {
    return $Call.ByID(3475289348, path);
}

/**
 * RemoveRadioFavourite removes a radio station from favourites.
 */
export function RemoveRadioFavourite(stationUUID: string): $CancellablePromise<void> {
    return $Call.ByID(876184048, stationUUID);
}

/**
 * RemoveTrackFromPlaylist removes a track from a playlist.
 */
export function RemoveTrackFromPlaylist(playlistID: number, trackID: number): $CancellablePromise<void> {
    return $Call.ByID(970681807, playlistID, trackID);
}

/**
 * RenamePlaylist renames a playlist.
 */
export function RenamePlaylist(id: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(3081673158, id, name);
}

/**
 * SaveAppPreferences stores product-level preferences.
 */
export function SaveAppPreferences(prefs: $models.AppPreferencesJSON): $CancellablePromise<void> {
    return $Call.ByID(1128588116, prefs);
}

/**
 * SaveScrobbleAPIKeys saves the Last.fm API key and secret.
 */
export function SaveScrobbleAPIKeys(apiKey: string, apiSecret: string): $CancellablePromise<void> {
    return $Call.ByID(1590775235, apiKey, apiSecret);
}

/**
 * ScanMusicLibrary scans all configured local music directories.
 */
export function ScanMusicLibrary(): $CancellablePromise<void> {
    return $Call.ByID(896031417);
}

/**
 * Search searches the library for tracks matching the query.
 */
export function Search(query: string, limit: number): $CancellablePromise<$models.SearchResult[]> {
    return $Call.ByID(2206755262, query, limit).then(($result: any) => {
        return $$createType31($result);
    });
}

/**
 * SearchRadioStations searches for radio stations by name.
 */
export function SearchRadioStations(query: string, limit: number): $CancellablePromise<$models.RadioStationJSON[]> {
    return $Call.ByID(1619368624, query, limit).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * SearchRadioStationsFiltered searches with optional country, codec, and tag filters.
 */
export function SearchRadioStationsFiltered(country: string, codec: string, tag: string, limit: number): $CancellablePromise<$models.RadioStationJSON[]> {
    return $Call.ByID(2804279923, country, codec, tag, limit).then(($result: any) => {
        return $$createType19($result);
    });
}

/**
 * SetListenBrainzEnabled toggles ListenBrainz scrobbling on or off.
 */
export function SetListenBrainzEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(333272068, enabled);
}

/**
 * SetRadioFavouritePinned pins or unpins a favourite station.
 */
export function SetRadioFavouritePinned(stationUUID: string, pinned: boolean): $CancellablePromise<void> {
    return $Call.ByID(2949163422, stationUUID, pinned);
}

/**
 * SetScrobbleEnabled toggles scrobbling on or off.
 */
export function SetScrobbleEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(22544365, enabled);
}

/**
 * SetThemePreference applies the current frontend theme to native desktop chrome.
 */
export function SetThemePreference(theme: string): $CancellablePromise<void> {
    return $Call.ByID(3763400674, theme);
}

/**
 * StartLastFmAuth begins the Last.fm auth flow: requests a token and opens
 * the browser for user approval. Returns the token for use with CompleteLastFmAuth.
 */
export function StartLastFmAuth(): $CancellablePromise<string> {
    return $Call.ByID(1558738173);
}

/**
 * SyncServers triggers an immediate sync of all server catalogs.
 */
export function SyncServers(): $CancellablePromise<void> {
    return $Call.ByID(545152779);
}

/**
 * TestConnection tests connectivity to a streaming server without persisting it.
 */
export function TestConnection(cfg: $models.ServerConfig): $CancellablePromise<void> {
    return $Call.ByID(3263505778, cfg);
}

/**
 * UpdateServer updates an existing streaming server configuration.
 */
export function UpdateServer(cfg: $models.ServerConfig): $CancellablePromise<void> {
    return $Call.ByID(1667032524, cfg);
}

// Private type creation functions
const $$createType0 = $models.RadioCustomStationJSON.createFrom;
const $$createType1 = $models.AlbumTrack.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.Album.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.AppPreferencesJSON.createFrom;
const $$createType6 = $models.ArtistInfoJSON.createFrom;
const $$createType7 = $Create.Array($$createType0);
const $$createType8 = $models.ListenBrainzConfigJSON.createFrom;
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = $models.PlaylistTrack.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.Playlist.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = $models.RadioFavouriteJSON.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = $models.RadioHistoryJSON.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = radio$0.StationView.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = $models.RecentPlayJSON.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = $models.ScrobbleConfigJSON.createFrom;
const $$createType23 = $models.ServerStatusJSON.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = $models.ServerConfig.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = $models.StatEntryJSON.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $models.UserConfigImportResultJSON.createFrom;
const $$createType30 = $models.SearchResult.createFrom;
const $$createType31 = $Create.Array($$createType30);
