// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService exposes the music library to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddServer adds a new streaming server configuration.
 * @param {$models.ServerConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function AddServer(cfg) {
    return $Call.ByID(477958106, cfg);
}

/**
 * AddTrackToPlaylist adds a track to a playlist.
 * @param {number} playlistID
 * @param {number} trackID
 * @returns {$CancellablePromise<void>}
 */
export function AddTrackToPlaylist(playlistID, trackID) {
    return $Call.ByID(2287316659, playlistID, trackID);
}

/**
 * AlbumArtwork returns the artwork for an album as a base64 data URI.
 * @param {number} albumID
 * @returns {$CancellablePromise<string>}
 */
export function AlbumArtwork(albumID) {
    return $Call.ByID(866920135, albumID);
}

/**
 * CompleteLastFmAuth exchanges the authorized token for a session key.
 * @param {string} token
 * @returns {$CancellablePromise<void>}
 */
export function CompleteLastFmAuth(token) {
    return $Call.ByID(3698942302, token);
}

/**
 * CreatePlaylist creates a new playlist and returns its ID.
 * @param {string} name
 * @returns {$CancellablePromise<number>}
 */
export function CreatePlaylist(name) {
    return $Call.ByID(4167498172, name);
}

/**
 * DeletePlaylist deletes a playlist.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeletePlaylist(id) {
    return $Call.ByID(2018893399, id);
}

/**
 * DeleteServer removes a streaming server configuration.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteServer(id) {
    return $Call.ByID(3862467038, id);
}

/**
 * DisconnectLastFm clears the Last.fm session key and username.
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectLastFm() {
    return $Call.ByID(970487533);
}

/**
 * GetAlbumTracks returns the tracks for a given album.
 * @param {number} albumID
 * @returns {$CancellablePromise<$models.AlbumTrack[]>}
 */
export function GetAlbumTracks(albumID) {
    return $Call.ByID(207489145, albumID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAlbums returns all albums sorted by the given field and direction.
 * Source: "" (all, deduped), "local", "server".
 * @param {string} sort
 * @param {string} order
 * @param {string} source
 * @returns {$CancellablePromise<$models.Album[]>}
 */
export function GetAlbums(sort, order, source) {
    return $Call.ByID(1337880606, sort, order, source).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetPlaylistTracks returns the tracks in a playlist.
 * @param {number} playlistID
 * @returns {$CancellablePromise<$models.PlaylistTrack[]>}
 */
export function GetPlaylistTracks(playlistID) {
    return $Call.ByID(4244880336, playlistID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetPlaylists returns all playlists.
 * @returns {$CancellablePromise<$models.Playlist[]>}
 */
export function GetPlaylists() {
    return $Call.ByID(1524576557).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetScrobbleConfig returns the current Last.fm scrobble configuration.
 * @returns {$CancellablePromise<$models.ScrobbleConfigJSON>}
 */
export function GetScrobbleConfig() {
    return $Call.ByID(3948527462).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetServerStatuses returns the online/offline status of all configured servers.
 * @returns {$CancellablePromise<$models.ServerStatusJSON[]>}
 */
export function GetServerStatuses() {
    return $Call.ByID(1839345631).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetServers returns all configured streaming servers.
 * @returns {$CancellablePromise<$models.ServerConfig[]>}
 */
export function GetServers() {
    return $Call.ByID(3711954650).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * MoveTrackInPlaylist moves a track from one position to another.
 * @param {number} playlistID
 * @param {number} fromPos
 * @param {number} toPos
 * @returns {$CancellablePromise<void>}
 */
export function MoveTrackInPlaylist(playlistID, fromPos, toPos) {
    return $Call.ByID(465154155, playlistID, fromPos, toPos);
}

/**
 * RemoveTrackFromPlaylist removes a track from a playlist.
 * @param {number} playlistID
 * @param {number} trackID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveTrackFromPlaylist(playlistID, trackID) {
    return $Call.ByID(970681807, playlistID, trackID);
}

/**
 * RenamePlaylist renames a playlist.
 * @param {number} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenamePlaylist(id, name) {
    return $Call.ByID(3081673158, id, name);
}

/**
 * SaveScrobbleAPIKeys saves the Last.fm API key and secret.
 * @param {string} apiKey
 * @param {string} apiSecret
 * @returns {$CancellablePromise<void>}
 */
export function SaveScrobbleAPIKeys(apiKey, apiSecret) {
    return $Call.ByID(1590775235, apiKey, apiSecret);
}

/**
 * Search searches the library for tracks matching the query.
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<$models.SearchResult[]>}
 */
export function Search(query, limit) {
    return $Call.ByID(2206755262, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * SetScrobbleEnabled toggles scrobbling on or off.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetScrobbleEnabled(enabled) {
    return $Call.ByID(22544365, enabled);
}

/**
 * StartLastFmAuth begins the Last.fm auth flow: requests a token and opens
 * the browser for user approval. Returns the token for use with CompleteLastFmAuth.
 * @returns {$CancellablePromise<string>}
 */
export function StartLastFmAuth() {
    return $Call.ByID(1558738173);
}

/**
 * SyncServers triggers an immediate sync of all server catalogs.
 * @returns {$CancellablePromise<void>}
 */
export function SyncServers() {
    return $Call.ByID(545152779);
}

/**
 * TestConnection tests connectivity to a streaming server without persisting it.
 * @param {$models.ServerConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function TestConnection(cfg) {
    return $Call.ByID(3263505778, cfg);
}

/**
 * UpdateServer updates an existing streaming server configuration.
 * @param {$models.ServerConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateServer(cfg) {
    return $Call.ByID(1667032524, cfg);
}

// Private type creation functions
const $$createType0 = $models.AlbumTrack.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Album.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.PlaylistTrack.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.Playlist.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.ScrobbleConfigJSON.createFrom;
const $$createType9 = $models.ServerStatusJSON.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.ServerConfig.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.SearchResult.createFrom;
const $$createType14 = $Create.Array($$createType13);
