// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService exposes the music library to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "./internal/library/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AlbumArtwork returns the artwork for an album as a base64 data URI.
 * @param {number} albumID
 * @returns {$CancellablePromise<string>}
 */
export function AlbumArtwork(albumID) {
    return $Call.ByID(866920135, albumID);
}

/**
 * GetAlbumTracks returns the tracks for a given album.
 * @param {number} albumID
 * @returns {$CancellablePromise<$models.AlbumTrack[]>}
 */
export function GetAlbumTracks(albumID) {
    return $Call.ByID(207489145, albumID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAlbums returns all albums sorted by the given field and direction.
 * @param {string} sort
 * @param {string} order
 * @returns {$CancellablePromise<$models.Album[]>}
 */
export function GetAlbums(sort, order) {
    return $Call.ByID(1337880606, sort, order).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Search searches the library for tracks matching the query.
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<library$0.SearchResult[]>}
 */
export function Search(query, limit) {
    return $Call.ByID(2206755262, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AlbumTrack.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.Album.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = library$0.SearchResult.createFrom;
const $$createType5 = $Create.Array($$createType4);
