// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Album is the JSON-friendly album type exposed to the frontend.
 */
export class Album {
    /**
     * Creates a new Album instance.
     * @param {Partial<Album>} [$$source = {}] - The source object to create the Album.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("year" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["year"] = 0;
        }
        if (!("trackCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackCount"] = 0;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Album instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Album}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Album(/** @type {Partial<Album>} */($$parsedSource));
    }
}

/**
 * AlbumTrack is the JSON-friendly track type exposed to the frontend.
 */
export class AlbumTrack {
    /**
     * Creates a new AlbumTrack instance.
     * @param {Partial<AlbumTrack>} [$$source = {}] - The source object to create the AlbumTrack.
     */
    constructor($$source = {}) {
        if (!("trackId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("trackNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackNumber"] = 0;
        }
        if (!("discNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["discNumber"] = 0;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumTrack instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AlbumTrack}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlbumTrack(/** @type {Partial<AlbumTrack>} */($$parsedSource));
    }
}

/**
 * Playlist is the JSON-friendly playlist type exposed to the frontend.
 */
export class Playlist {
    /**
     * Creates a new Playlist instance.
     * @param {Partial<Playlist>} [$$source = {}] - The source object to create the Playlist.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Playlist instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Playlist}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Playlist(/** @type {Partial<Playlist>} */($$parsedSource));
    }
}

/**
 * PlaylistTrack is the JSON-friendly playlist track type exposed to the frontend.
 */
export class PlaylistTrack {
    /**
     * Creates a new PlaylistTrack instance.
     * @param {Partial<PlaylistTrack>} [$$source = {}] - The source object to create the PlaylistTrack.
     */
    constructor($$source = {}) {
        if (!("trackId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["album"] = "";
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["position"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistTrack instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlaylistTrack}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaylistTrack(/** @type {Partial<PlaylistTrack>} */($$parsedSource));
    }
}

/**
 * ServerConfig is the JSON-friendly server configuration type exposed to the frontend.
 */
export class ServerConfig {
    /**
     * Creates a new ServerConfig instance.
     * @param {Partial<ServerConfig>} [$$source = {}] - The source object to create the ServerConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerConfig(/** @type {Partial<ServerConfig>} */($$parsedSource));
    }
}
