// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Album is the JSON-friendly album type exposed to the frontend.
 */
export class Album {
    "id": number;
    "title": string;
    "artist": string;
    "year": number;
    "trackCount": number;

    /** Creates a new Album instance. */
    constructor($$source: Partial<Album> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("year" in $$source)) {
            this["year"] = 0;
        }
        if (!("trackCount" in $$source)) {
            this["trackCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Album instance from a string or object.
     */
    static createFrom($$source: any = {}): Album {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Album($$parsedSource as Partial<Album>);
    }
}

/**
 * AlbumTrack is the JSON-friendly track type exposed to the frontend.
 */
export class AlbumTrack {
    "trackId": number;
    "title": string;
    "artist": string;
    "trackNumber": number;
    "discNumber": number;
    "durationMs": number;
    "filePath": string;

    /** Creates a new AlbumTrack instance. */
    constructor($$source: Partial<AlbumTrack> = {}) {
        if (!("trackId" in $$source)) {
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("trackNumber" in $$source)) {
            this["trackNumber"] = 0;
        }
        if (!("discNumber" in $$source)) {
            this["discNumber"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumTrack instance from a string or object.
     */
    static createFrom($$source: any = {}): AlbumTrack {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlbumTrack($$parsedSource as Partial<AlbumTrack>);
    }
}

/**
 * Playlist is the JSON-friendly playlist type exposed to the frontend.
 */
export class Playlist {
    "id": number;
    "name": string;

    /** Creates a new Playlist instance. */
    constructor($$source: Partial<Playlist> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Playlist instance from a string or object.
     */
    static createFrom($$source: any = {}): Playlist {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Playlist($$parsedSource as Partial<Playlist>);
    }
}

/**
 * PlaylistTrack is the JSON-friendly playlist track type exposed to the frontend.
 */
export class PlaylistTrack {
    "trackId": number;
    "title": string;
    "artist": string;
    "album": string;
    "durationMs": number;
    "filePath": string;
    "position": number;

    /** Creates a new PlaylistTrack instance. */
    constructor($$source: Partial<PlaylistTrack> = {}) {
        if (!("trackId" in $$source)) {
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            this["album"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistTrack instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaylistTrack {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaylistTrack($$parsedSource as Partial<PlaylistTrack>);
    }
}
