// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Album is the JSON-friendly album type exposed to the frontend.
 */
export class Album {
    /**
     * Creates a new Album instance.
     * @param {Partial<Album>} [$$source = {}] - The source object to create the Album.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("year" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["year"] = 0;
        }
        if (!("trackCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackCount"] = 0;
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("serverId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Album instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Album}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Album(/** @type {Partial<Album>} */($$parsedSource));
    }
}

/**
 * AlbumTrack is the JSON-friendly track type exposed to the frontend.
 */
export class AlbumTrack {
    /**
     * Creates a new AlbumTrack instance.
     * @param {Partial<AlbumTrack>} [$$source = {}] - The source object to create the AlbumTrack.
     */
    constructor($$source = {}) {
        if (!("trackId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("trackNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackNumber"] = 0;
        }
        if (!("discNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["discNumber"] = 0;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("serverId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumTrack instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AlbumTrack}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlbumTrack(/** @type {Partial<AlbumTrack>} */($$parsedSource));
    }
}

/**
 * ListenBrainzConfigJSON is the JSON-friendly ListenBrainz config exposed to the frontend.
 * UserToken is intentionally omitted.
 */
export class ListenBrainzConfigJSON {
    /**
     * Creates a new ListenBrainzConfigJSON instance.
     * @param {Partial<ListenBrainzConfigJSON>} [$$source = {}] - The source object to create the ListenBrainzConfigJSON.
     */
    constructor($$source = {}) {
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListenBrainzConfigJSON instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListenBrainzConfigJSON}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListenBrainzConfigJSON(/** @type {Partial<ListenBrainzConfigJSON>} */($$parsedSource));
    }
}

/**
 * Playlist is the JSON-friendly playlist type exposed to the frontend.
 */
export class Playlist {
    /**
     * Creates a new Playlist instance.
     * @param {Partial<Playlist>} [$$source = {}] - The source object to create the Playlist.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Playlist instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Playlist}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Playlist(/** @type {Partial<Playlist>} */($$parsedSource));
    }
}

/**
 * PlaylistTrack is the JSON-friendly playlist track type exposed to the frontend.
 */
export class PlaylistTrack {
    /**
     * Creates a new PlaylistTrack instance.
     * @param {Partial<PlaylistTrack>} [$$source = {}] - The source object to create the PlaylistTrack.
     */
    constructor($$source = {}) {
        if (!("trackId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["album"] = "";
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["position"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistTrack instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlaylistTrack}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaylistTrack(/** @type {Partial<PlaylistTrack>} */($$parsedSource));
    }
}

/**
 * RecentPlayJSON is the JSON-friendly recent play type exposed to the frontend.
 */
export class RecentPlayJSON {
    /**
     * Creates a new RecentPlayJSON instance.
     * @param {Partial<RecentPlayJSON>} [$$source = {}] - The source object to create the RecentPlayJSON.
     */
    constructor($$source = {}) {
        if (!("trackId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["album"] = "";
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("playedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["playedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecentPlayJSON instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RecentPlayJSON}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecentPlayJSON(/** @type {Partial<RecentPlayJSON>} */($$parsedSource));
    }
}

/**
 * ScrobbleConfigJSON is the JSON-friendly scrobble config exposed to the frontend.
 * APISecret is intentionally omitted.
 */
export class ScrobbleConfigJSON {
    /**
     * Creates a new ScrobbleConfigJSON instance.
     * @param {Partial<ScrobbleConfigJSON>} [$$source = {}] - The source object to create the ScrobbleConfigJSON.
     */
    constructor($$source = {}) {
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("sessionKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionKey"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScrobbleConfigJSON instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScrobbleConfigJSON}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScrobbleConfigJSON(/** @type {Partial<ScrobbleConfigJSON>} */($$parsedSource));
    }
}

/**
 * SearchResult is the JSON-friendly search result type exposed to the frontend.
 */
export class SearchResult {
    /**
     * Creates a new SearchResult instance.
     * @param {Partial<SearchResult>} [$$source = {}] - The source object to create the SearchResult.
     */
    constructor($$source = {}) {
        if (!("trackId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["album"] = "";
        }
        if (!("genre" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["genre"] = "";
        }
        if (!("trackNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackNumber"] = 0;
        }
        if (!("discNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["discNumber"] = 0;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("serverId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SearchResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult(/** @type {Partial<SearchResult>} */($$parsedSource));
    }
}

/**
 * ServerConfig is the JSON-friendly server configuration type exposed to the frontend.
 */
export class ServerConfig {
    /**
     * Creates a new ServerConfig instance.
     * @param {Partial<ServerConfig>} [$$source = {}] - The source object to create the ServerConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerConfig(/** @type {Partial<ServerConfig>} */($$parsedSource));
    }
}

/**
 * ServerStatusJSON is the JSON-friendly server status type exposed to the frontend.
 */
export class ServerStatusJSON {
    /**
     * Creates a new ServerStatusJSON instance.
     * @param {Partial<ServerStatusJSON>} [$$source = {}] - The source object to create the ServerStatusJSON.
     */
    constructor($$source = {}) {
        if (!("serverId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("online" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["online"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStatusJSON instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerStatusJSON}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerStatusJSON(/** @type {Partial<ServerStatusJSON>} */($$parsedSource));
    }
}

/**
 * StatEntryJSON is the JSON-friendly stat entry type exposed to the frontend.
 */
export class StatEntryJSON {
    /**
     * Creates a new StatEntryJSON instance.
     * @param {Partial<StatEntryJSON>} [$$source = {}] - The source object to create the StatEntryJSON.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("secondLine" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["secondLine"] = "";
        }
        if (!("playCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["playCount"] = 0;
        }
        if (!("totalMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatEntryJSON instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatEntryJSON}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatEntryJSON(/** @type {Partial<StatEntryJSON>} */($$parsedSource));
    }
}
