// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Album is the JSON-friendly album type exposed to the frontend.
 */
export class Album {
    /**
     * Creates a new Album instance.
     * @param {Partial<Album>} [$$source = {}] - The source object to create the Album.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("year" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["year"] = 0;
        }
        if (!("trackCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Album instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Album}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Album(/** @type {Partial<Album>} */($$parsedSource));
    }
}

/**
 * AlbumTrack is the JSON-friendly track type exposed to the frontend.
 */
export class AlbumTrack {
    /**
     * Creates a new AlbumTrack instance.
     * @param {Partial<AlbumTrack>} [$$source = {}] - The source object to create the AlbumTrack.
     */
    constructor($$source = {}) {
        if (!("trackId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("trackNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trackNumber"] = 0;
        }
        if (!("discNumber" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["discNumber"] = 0;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumTrack instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AlbumTrack}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlbumTrack(/** @type {Partial<AlbumTrack>} */($$parsedSource));
    }
}
