// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Album is the JSON-friendly album type exposed to the frontend.
 */
export class Album {
    "id": number;
    "title": string;
    "artist": string;
    "year": number;
    "trackCount": number;
    "source": string;
    "serverId": string;

    /** Creates a new Album instance. */
    constructor($$source: Partial<Album> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("year" in $$source)) {
            this["year"] = 0;
        }
        if (!("trackCount" in $$source)) {
            this["trackCount"] = 0;
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Album instance from a string or object.
     */
    static createFrom($$source: any = {}): Album {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Album($$parsedSource as Partial<Album>);
    }
}

/**
 * AlbumTrack is the JSON-friendly track type exposed to the frontend.
 */
export class AlbumTrack {
    "trackId": number;
    "title": string;
    "artist": string;
    "trackNumber": number;
    "discNumber": number;
    "durationMs": number;
    "filePath": string;
    "source": string;
    "serverId": string;

    /** Creates a new AlbumTrack instance. */
    constructor($$source: Partial<AlbumTrack> = {}) {
        if (!("trackId" in $$source)) {
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("trackNumber" in $$source)) {
            this["trackNumber"] = 0;
        }
        if (!("discNumber" in $$source)) {
            this["discNumber"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlbumTrack instance from a string or object.
     */
    static createFrom($$source: any = {}): AlbumTrack {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlbumTrack($$parsedSource as Partial<AlbumTrack>);
    }
}

/**
 * ListenBrainzConfigJSON is the JSON-friendly ListenBrainz config exposed to the frontend.
 * UserToken is intentionally omitted.
 */
export class ListenBrainzConfigJSON {
    "username": string;
    "enabled": boolean;

    /** Creates a new ListenBrainzConfigJSON instance. */
    constructor($$source: Partial<ListenBrainzConfigJSON> = {}) {
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListenBrainzConfigJSON instance from a string or object.
     */
    static createFrom($$source: any = {}): ListenBrainzConfigJSON {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListenBrainzConfigJSON($$parsedSource as Partial<ListenBrainzConfigJSON>);
    }
}

/**
 * Playlist is the JSON-friendly playlist type exposed to the frontend.
 */
export class Playlist {
    "id": number;
    "name": string;

    /** Creates a new Playlist instance. */
    constructor($$source: Partial<Playlist> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Playlist instance from a string or object.
     */
    static createFrom($$source: any = {}): Playlist {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Playlist($$parsedSource as Partial<Playlist>);
    }
}

/**
 * PlaylistTrack is the JSON-friendly playlist track type exposed to the frontend.
 */
export class PlaylistTrack {
    "trackId": number;
    "title": string;
    "artist": string;
    "album": string;
    "durationMs": number;
    "filePath": string;
    "position": number;

    /** Creates a new PlaylistTrack instance. */
    constructor($$source: Partial<PlaylistTrack> = {}) {
        if (!("trackId" in $$source)) {
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            this["album"] = "";
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaylistTrack instance from a string or object.
     */
    static createFrom($$source: any = {}): PlaylistTrack {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PlaylistTrack($$parsedSource as Partial<PlaylistTrack>);
    }
}

/**
 * ScrobbleConfigJSON is the JSON-friendly scrobble config exposed to the frontend.
 * APISecret is intentionally omitted.
 */
export class ScrobbleConfigJSON {
    "apiKey": string;
    "sessionKey": string;
    "username": string;
    "enabled": boolean;

    /** Creates a new ScrobbleConfigJSON instance. */
    constructor($$source: Partial<ScrobbleConfigJSON> = {}) {
        if (!("apiKey" in $$source)) {
            this["apiKey"] = "";
        }
        if (!("sessionKey" in $$source)) {
            this["sessionKey"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScrobbleConfigJSON instance from a string or object.
     */
    static createFrom($$source: any = {}): ScrobbleConfigJSON {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScrobbleConfigJSON($$parsedSource as Partial<ScrobbleConfigJSON>);
    }
}

/**
 * SearchResult is the JSON-friendly search result type exposed to the frontend.
 */
export class SearchResult {
    "trackId": number;
    "title": string;
    "artist": string;
    "album": string;
    "genre": string;
    "trackNumber": number;
    "discNumber": number;
    "durationMs": number;
    "filePath": string;
    "source": string;
    "serverId": string;

    /** Creates a new SearchResult instance. */
    constructor($$source: Partial<SearchResult> = {}) {
        if (!("trackId" in $$source)) {
            this["trackId"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("artist" in $$source)) {
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            this["album"] = "";
        }
        if (!("genre" in $$source)) {
            this["genre"] = "";
        }
        if (!("trackNumber" in $$source)) {
            this["trackNumber"] = 0;
        }
        if (!("discNumber" in $$source)) {
            this["discNumber"] = 0;
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchResult($$parsedSource as Partial<SearchResult>);
    }
}

/**
 * ServerConfig is the JSON-friendly server configuration type exposed to the frontend.
 */
export class ServerConfig {
    "id": string;
    "name": string;
    "type": string;
    "url": string;
    "username": string;
    "password": string;

    /** Creates a new ServerConfig instance. */
    constructor($$source: Partial<ServerConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("username" in $$source)) {
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerConfig($$parsedSource as Partial<ServerConfig>);
    }
}

/**
 * ServerStatusJSON is the JSON-friendly server status type exposed to the frontend.
 */
export class ServerStatusJSON {
    "serverId": string;
    "name": string;
    "online": boolean;

    /** Creates a new ServerStatusJSON instance. */
    constructor($$source: Partial<ServerStatusJSON> = {}) {
        if (!("serverId" in $$source)) {
            this["serverId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("online" in $$source)) {
            this["online"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStatusJSON instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerStatusJSON {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ServerStatusJSON($$parsedSource as Partial<ServerStatusJSON>);
    }
}
