// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlayerService exposes audio playback controls to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Play starts playback of the audio file at the given path.
 */
export function Play(path: string): $CancellablePromise<void> {
    return $Call.ByID(1808111650, path);
}

/**
 * Playing reports whether audio is currently playing.
 */
export function Playing(): $CancellablePromise<boolean> {
    return $Call.ByID(2882669630);
}

/**
 * Stop halts the current playback.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2311398648);
}

/**
 * Version returns the mpv library version string.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(1040332204);
}
