// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlayerService exposes audio playback controls to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as player$0 from "./internal/player/models.js";

/**
 * Artwork returns the album artwork for the currently playing track
 * as a base64-encoded data URI, or an empty string if unavailable.
 * @returns {$CancellablePromise<string>}
 */
export function Artwork() {
    return $Call.ByID(468839008);
}

/**
 * Duration returns the duration of the current track in seconds.
 * @returns {$CancellablePromise<number>}
 */
export function Duration() {
    return $Call.ByID(1985222848);
}

/**
 * Enqueue appends a track to the playlist for gapless playback.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Enqueue(path) {
    return $Call.ByID(1683307842, path);
}

/**
 * GetNotifications returns whether desktop notifications are enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetNotifications() {
    return $Call.ByID(3578942832);
}

/**
 * GetQueue returns all tracks in the queue.
 * @returns {$CancellablePromise<player$0.QueueTrack[]>}
 */
export function GetQueue() {
    return $Call.ByID(1525514291).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetQueuePosition returns the current queue position (-1 if empty).
 * @returns {$CancellablePromise<number>}
 */
export function GetQueuePosition() {
    return $Call.ByID(752141504);
}

/**
 * GetRepeat returns the current repeat mode as a string.
 * @returns {$CancellablePromise<string>}
 */
export function GetRepeat() {
    return $Call.ByID(3949558547);
}

/**
 * GetShuffle returns whether shuffle mode is active.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetShuffle() {
    return $Call.ByID(4278779269);
}

/**
 * GetToasts returns and clears all pending toast notifications.
 * @returns {$CancellablePromise<player$0.Toast[]>}
 */
export function GetToasts() {
    return $Call.ByID(327853480).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * IsRadioMode returns whether the player is currently in radio mode.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsRadioMode() {
    return $Call.ByID(2964685828);
}

/**
 * MediaAlbum returns the album of the currently playing track.
 * @returns {$CancellablePromise<string>}
 */
export function MediaAlbum() {
    return $Call.ByID(3994078579);
}

/**
 * MediaArtist returns the artist of the currently playing track.
 * @returns {$CancellablePromise<string>}
 */
export function MediaArtist() {
    return $Call.ByID(3929664599);
}

/**
 * MediaPath returns the file path of the currently playing track.
 * @returns {$CancellablePromise<string>}
 */
export function MediaPath() {
    return $Call.ByID(3316771859);
}

/**
 * MediaTitle returns the title of the currently playing track.
 * @returns {$CancellablePromise<string>}
 */
export function MediaTitle() {
    return $Call.ByID(3116228434);
}

/**
 * Next skips to the next track in the queue.
 * @returns {$CancellablePromise<void>}
 */
export function Next() {
    return $Call.ByID(1009561457);
}

/**
 * Pause pauses the current playback.
 * @returns {$CancellablePromise<void>}
 */
export function Pause() {
    return $Call.ByID(191671602);
}

/**
 * Play starts playback of the audio file at the given path.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Play(path) {
    return $Call.ByID(1808111650, path);
}

/**
 * PlayAll replaces the playlist and plays the given tracks in order.
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function PlayAll(paths) {
    return $Call.ByID(3674799417, paths);
}

/**
 * PlayQueue replaces the queue with the given tracks and starts playback
 * from startAt. This is the primary entry point for playing from the UI.
 * @param {player$0.QueueTrack[]} tracks
 * @param {number} startAt
 * @returns {$CancellablePromise<void>}
 */
export function PlayQueue(tracks, startAt) {
    return $Call.ByID(3857677157, tracks, startAt);
}

/**
 * PlayRadio starts playback of a radio stream. It saves the current library
 * queue and enters radio mode where next/prev/shuffle/repeat are disabled.
 * @param {string} stationName
 * @param {string} streamURL
 * @param {string} artworkURL
 * @returns {$CancellablePromise<void>}
 */
export function PlayRadio(stationName, streamURL, artworkURL) {
    return $Call.ByID(1236378929, stationName, streamURL, artworkURL);
}

/**
 * Position returns the current playback position in seconds.
 * @returns {$CancellablePromise<number>}
 */
export function Position() {
    return $Call.ByID(3379668963);
}

/**
 * Previous skips to the previous track in the queue.
 * @returns {$CancellablePromise<void>}
 */
export function Previous() {
    return $Call.ByID(2487521925);
}

/**
 * QueueAppend adds a track to the end of the queue.
 * If nothing is playing, it does not start playback.
 * @param {player$0.QueueTrack} track
 * @returns {$CancellablePromise<void>}
 */
export function QueueAppend(track) {
    return $Call.ByID(3799532135, track);
}

/**
 * QueueClear clears the queue and stops playback.
 * @returns {$CancellablePromise<void>}
 */
export function QueueClear() {
    return $Call.ByID(3052298016);
}

/**
 * QueueInsertNext inserts a track immediately after the current track.
 * @param {player$0.QueueTrack} track
 * @returns {$CancellablePromise<void>}
 */
export function QueueInsertNext(track) {
    return $Call.ByID(125730107, track);
}

/**
 * QueueMove moves a track from one position to another.
 * @param {number} $from
 * @param {number} to
 * @returns {$CancellablePromise<void>}
 */
export function QueueMove($from, to) {
    return $Call.ByID(3873105318, $from, to);
}

/**
 * QueueRemove removes the track at the given index.
 * If the removed track was the current track, playback restarts from
 * the new current position.
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function QueueRemove(index) {
    return $Call.ByID(1743380467, index);
}

/**
 * RadioArtworkURL returns the artwork URL of the currently playing radio station.
 * @returns {$CancellablePromise<string>}
 */
export function RadioArtworkURL() {
    return $Call.ByID(1282363134);
}

/**
 * RadioStationName returns the name of the currently playing radio station.
 * @returns {$CancellablePromise<string>}
 */
export function RadioStationName() {
    return $Call.ByID(2576550642);
}

/**
 * ReplayGain returns the current ReplayGain mode.
 * @returns {$CancellablePromise<string>}
 */
export function ReplayGain() {
    return $Call.ByID(3252990072);
}

/**
 * Resume resumes paused playback.
 * @returns {$CancellablePromise<void>}
 */
export function Resume() {
    return $Call.ByID(4192344979);
}

/**
 * Seek seeks to the given position in seconds.
 * @param {number} seconds
 * @returns {$CancellablePromise<void>}
 */
export function Seek(seconds) {
    return $Call.ByID(1479346536, seconds);
}

/**
 * SetNotifications enables or disables desktop notifications.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetNotifications(enabled) {
    return $Call.ByID(2522355060, enabled);
}

/**
 * SetRepeat sets the repeat mode: "off", "all", or "one".
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetRepeat(mode) {
    return $Call.ByID(76083775, mode);
}

/**
 * SetReplayGain sets the ReplayGain mode: "track", "album", or "no" (off).
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetReplayGain(mode) {
    return $Call.ByID(804885384, mode);
}

/**
 * SetShuffle enables or disables shuffle mode.
 * When toggled, the mpv playlist is rebuilt to match the new order.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetShuffle(enabled) {
    return $Call.ByID(3896707945, enabled);
}

/**
 * SetVolume sets the volume (0-100).
 * @param {number} percent
 * @returns {$CancellablePromise<void>}
 */
export function SetVolume(percent) {
    return $Call.ByID(671101282, percent);
}

/**
 * State returns the current playback state as a string.
 * @returns {$CancellablePromise<string>}
 */
export function State() {
    return $Call.ByID(2570357237);
}

/**
 * Stop halts the current playback.
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2311398648);
}

/**
 * StopRadio stops the current radio stream and restores the library queue.
 * @returns {$CancellablePromise<void>}
 */
export function StopRadio() {
    return $Call.ByID(3776601259);
}

/**
 * Version returns the mpv library version string.
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(1040332204);
}

/**
 * Volume returns the current volume (0-100).
 * @returns {$CancellablePromise<number>}
 */
export function Volume() {
    return $Call.ByID(2798880050);
}

// Private type creation functions
const $$createType0 = player$0.QueueTrack.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = player$0.Toast.createFrom;
const $$createType3 = $Create.Array($$createType2);
