// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlayerService exposes audio playback controls to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * Artwork returns the album artwork for the currently playing track
 * as a base64-encoded data URI, or an empty string if unavailable.
 * @returns {$CancellablePromise<string>}
 */
export function Artwork() {
    return $Call.ByID(468839008);
}

/**
 * Duration returns the duration of the current track in seconds.
 * @returns {$CancellablePromise<number>}
 */
export function Duration() {
    return $Call.ByID(1985222848);
}

/**
 * Enqueue appends a track to the playlist for gapless playback.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Enqueue(path) {
    return $Call.ByID(1683307842, path);
}

/**
 * MediaAlbum returns the album of the currently playing track.
 * @returns {$CancellablePromise<string>}
 */
export function MediaAlbum() {
    return $Call.ByID(3994078579);
}

/**
 * MediaArtist returns the artist of the currently playing track.
 * @returns {$CancellablePromise<string>}
 */
export function MediaArtist() {
    return $Call.ByID(3929664599);
}

/**
 * MediaTitle returns the title of the currently playing track.
 * @returns {$CancellablePromise<string>}
 */
export function MediaTitle() {
    return $Call.ByID(3116228434);
}

/**
 * Next skips to the next track in the playlist.
 * @returns {$CancellablePromise<void>}
 */
export function Next() {
    return $Call.ByID(1009561457);
}

/**
 * Pause pauses the current playback.
 * @returns {$CancellablePromise<void>}
 */
export function Pause() {
    return $Call.ByID(191671602);
}

/**
 * Play starts playback of the audio file at the given path.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function Play(path) {
    return $Call.ByID(1808111650, path);
}

/**
 * PlayAll replaces the playlist and plays the given tracks in order.
 * @param {string[]} paths
 * @returns {$CancellablePromise<void>}
 */
export function PlayAll(paths) {
    return $Call.ByID(3674799417, paths);
}

/**
 * Position returns the current playback position in seconds.
 * @returns {$CancellablePromise<number>}
 */
export function Position() {
    return $Call.ByID(3379668963);
}

/**
 * Previous skips to the previous track in the playlist.
 * @returns {$CancellablePromise<void>}
 */
export function Previous() {
    return $Call.ByID(2487521925);
}

/**
 * ReplayGain returns the current ReplayGain mode.
 * @returns {$CancellablePromise<string>}
 */
export function ReplayGain() {
    return $Call.ByID(3252990072);
}

/**
 * Resume resumes paused playback.
 * @returns {$CancellablePromise<void>}
 */
export function Resume() {
    return $Call.ByID(4192344979);
}

/**
 * Seek seeks to the given position in seconds.
 * @param {number} seconds
 * @returns {$CancellablePromise<void>}
 */
export function Seek(seconds) {
    return $Call.ByID(1479346536, seconds);
}

/**
 * SetReplayGain sets the ReplayGain mode: "track", "album", or "no" (off).
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetReplayGain(mode) {
    return $Call.ByID(804885384, mode);
}

/**
 * SetVolume sets the volume (0-100).
 * @param {number} percent
 * @returns {$CancellablePromise<void>}
 */
export function SetVolume(percent) {
    return $Call.ByID(671101282, percent);
}

/**
 * State returns the current playback state as a string.
 * @returns {$CancellablePromise<string>}
 */
export function State() {
    return $Call.ByID(2570357237);
}

/**
 * Stop halts the current playback.
 * @returns {$CancellablePromise<void>}
 */
export function Stop() {
    return $Call.ByID(2311398648);
}

/**
 * Version returns the mpv library version string.
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(1040332204);
}

/**
 * Volume returns the current volume (0-100).
 * @returns {$CancellablePromise<number>}
 */
export function Volume() {
    return $Call.ByID(2798880050);
}
