// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PlayerService exposes audio playback controls to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as player$0 from "./internal/player/models.js";

/**
 * Artwork returns the album artwork for the currently playing track
 * as a base64-encoded data URI, or an empty string if unavailable.
 */
export function Artwork(): $CancellablePromise<string> {
    return $Call.ByID(468839008);
}

/**
 * Duration returns the duration of the current track in seconds.
 */
export function Duration(): $CancellablePromise<number> {
    return $Call.ByID(1985222848);
}

/**
 * Enqueue appends a track to the playlist for gapless playback.
 */
export function Enqueue(path: string): $CancellablePromise<void> {
    return $Call.ByID(1683307842, path);
}

/**
 * GetNotifications returns whether desktop notifications are enabled.
 */
export function GetNotifications(): $CancellablePromise<boolean> {
    return $Call.ByID(3578942832);
}

/**
 * GetQueue returns all tracks in the queue.
 */
export function GetQueue(): $CancellablePromise<player$0.QueueTrack[]> {
    return $Call.ByID(1525514291).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetQueuePosition returns the current queue position (-1 if empty).
 */
export function GetQueuePosition(): $CancellablePromise<number> {
    return $Call.ByID(752141504);
}

/**
 * GetRepeat returns the current repeat mode as a string.
 */
export function GetRepeat(): $CancellablePromise<string> {
    return $Call.ByID(3949558547);
}

/**
 * GetShuffle returns whether shuffle mode is active.
 */
export function GetShuffle(): $CancellablePromise<boolean> {
    return $Call.ByID(4278779269);
}

/**
 * MediaAlbum returns the album of the currently playing track.
 */
export function MediaAlbum(): $CancellablePromise<string> {
    return $Call.ByID(3994078579);
}

/**
 * MediaArtist returns the artist of the currently playing track.
 */
export function MediaArtist(): $CancellablePromise<string> {
    return $Call.ByID(3929664599);
}

/**
 * MediaPath returns the file path of the currently playing track.
 */
export function MediaPath(): $CancellablePromise<string> {
    return $Call.ByID(3316771859);
}

/**
 * MediaTitle returns the title of the currently playing track.
 */
export function MediaTitle(): $CancellablePromise<string> {
    return $Call.ByID(3116228434);
}

/**
 * Next skips to the next track in the queue.
 */
export function Next(): $CancellablePromise<void> {
    return $Call.ByID(1009561457);
}

/**
 * Pause pauses the current playback.
 */
export function Pause(): $CancellablePromise<void> {
    return $Call.ByID(191671602);
}

/**
 * Play starts playback of the audio file at the given path.
 */
export function Play(path: string): $CancellablePromise<void> {
    return $Call.ByID(1808111650, path);
}

/**
 * PlayAll replaces the playlist and plays the given tracks in order.
 */
export function PlayAll(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(3674799417, paths);
}

/**
 * PlayQueue replaces the queue with the given tracks and starts playback
 * from startAt. This is the primary entry point for playing from the UI.
 */
export function PlayQueue(tracks: player$0.QueueTrack[], startAt: number): $CancellablePromise<void> {
    return $Call.ByID(3857677157, tracks, startAt);
}

/**
 * Position returns the current playback position in seconds.
 */
export function Position(): $CancellablePromise<number> {
    return $Call.ByID(3379668963);
}

/**
 * Previous skips to the previous track in the queue.
 */
export function Previous(): $CancellablePromise<void> {
    return $Call.ByID(2487521925);
}

/**
 * QueueAppend adds a track to the end of the queue.
 * If nothing is playing, it does not start playback.
 */
export function QueueAppend(track: player$0.QueueTrack): $CancellablePromise<void> {
    return $Call.ByID(3799532135, track);
}

/**
 * QueueClear clears the queue and stops playback.
 */
export function QueueClear(): $CancellablePromise<void> {
    return $Call.ByID(3052298016);
}

/**
 * QueueInsertNext inserts a track immediately after the current track.
 */
export function QueueInsertNext(track: player$0.QueueTrack): $CancellablePromise<void> {
    return $Call.ByID(125730107, track);
}

/**
 * QueueMove moves a track from one position to another.
 */
export function QueueMove($from: number, to: number): $CancellablePromise<void> {
    return $Call.ByID(3873105318, $from, to);
}

/**
 * QueueRemove removes the track at the given index.
 * If the removed track was the current track, playback restarts from
 * the new current position.
 */
export function QueueRemove(index: number): $CancellablePromise<void> {
    return $Call.ByID(1743380467, index);
}

/**
 * ReplayGain returns the current ReplayGain mode.
 */
export function ReplayGain(): $CancellablePromise<string> {
    return $Call.ByID(3252990072);
}

/**
 * Resume resumes paused playback.
 */
export function Resume(): $CancellablePromise<void> {
    return $Call.ByID(4192344979);
}

/**
 * Seek seeks to the given position in seconds.
 */
export function Seek(seconds: number): $CancellablePromise<void> {
    return $Call.ByID(1479346536, seconds);
}

/**
 * SetNotifications enables or disables desktop notifications.
 */
export function SetNotifications(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2522355060, enabled);
}

/**
 * SetRepeat sets the repeat mode: "off", "all", or "one".
 */
export function SetRepeat(mode: string): $CancellablePromise<void> {
    return $Call.ByID(76083775, mode);
}

/**
 * SetReplayGain sets the ReplayGain mode: "track", "album", or "no" (off).
 */
export function SetReplayGain(mode: string): $CancellablePromise<void> {
    return $Call.ByID(804885384, mode);
}

/**
 * SetShuffle enables or disables shuffle mode.
 * When toggled, the mpv playlist is rebuilt to match the new order.
 */
export function SetShuffle(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3896707945, enabled);
}

/**
 * SetVolume sets the volume (0-100).
 */
export function SetVolume(percent: number): $CancellablePromise<void> {
    return $Call.ByID(671101282, percent);
}

/**
 * State returns the current playback state as a string.
 */
export function State(): $CancellablePromise<string> {
    return $Call.ByID(2570357237);
}

/**
 * Stop halts the current playback.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(2311398648);
}

/**
 * Version returns the mpv library version string.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(1040332204);
}

/**
 * Volume returns the current volume (0-100).
 */
export function Volume(): $CancellablePromise<number> {
    return $Call.ByID(2798880050);
}

// Private type creation functions
const $$createType0 = player$0.QueueTrack.createFrom;
const $$createType1 = $Create.Array($$createType0);
